[package]
name = "bake"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12"
chrono = { version = "0.4", features = ["serde"] }
matter = { git = "https://github.com/vallentin/matter" }
pulldown-cmark = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
